
-- BATCH STUDENT SEEDING (Sutherland Data Scientist Role)
-- Generated on: 2026-04-30T06:22:38.904Z

INSERT INTO public.students (
    sap_id, name, email, phone, branch, current_year, batch, cgpa, 
    linkedin_url, github_url, leetcode_username, leetcode_total_solved, 
    achievements, skills
)
VALUES 
('70572200036', 'Rachit Jain', 'rachit.jain036@nmims.edu.in', '96196088099', 'B.Tech CSE (DS)', 4, '2022-26', 8.40, 'https://www.linkedin.com/in/rachitjain24/', 'https://github.com/Rachit-Jain-24', 'Rachitjain10', 60, to_jsonb(ARRAY['Received official Letter of Appreciation from the Additional District Collector, Mahabubnagar, for developing and deploying a district-level mobile & web application (MBNR Vidya Eye) used across 100+ government hostels to enhance transparency and digital governance. Published 1 IEEE conference paper (IEEE Xplore indexed) and 1 IEEE paper accepted for publication. Top 20 Finalist in AWS GenAI Hackathon 2025. AWS Certified Cloud Practitioner.', 'AWS Gen AI (Top 20); Analytics Vidya DataHack; Webathon 2.0; Webathon 1.0; Amazon ML Hackathon 2025']), ARRAY['Python', 'SQL', 'Machine Learning', 'GenAI', 'Prompt Engineering']),
('70572200010', 'Kapperi Divya Sri', 'divya.sri010@nmims.edu.in', '9347220561', 'B.Tech CSE (DS)', 4, '2022-26', 8.80, 'linkedin.com/in/divya-reddy-kapperi-589bb9250', 'https://github.com/DivyaReddy0561', 'Divya_sri_Kapperi', 28, to_jsonb(ARRAY['Selected for ACM Summer School sponsored by Google at IMSC Chennai; Vice President of Student Council STME NMIMS HYD']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'Computer Vision', 'Tableau']),
('70572200011', 'Pavithra Sevakula', 'pavithra.sevakula011@nmims.edu.in', '7032254253', 'B.Tech CSE (DS)', 4, '2022-26', 9.22, 'https://www.linkedin.com/in/pavithra-sevakula/', 'https://github.com/Pavithrasevakula', 'pavithrasevakula011', 23, to_jsonb(ARRAY['Selected twice for ACM Schools organised by ACM India under the themes of "Data Science for Social Good" and  "AI for Social Good" ; Published Research Papers in reputed conferences like IEEE.', 'Amazon ML Hackathon 2025, Anaverse 2.0(top 10%)']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'AWS', 'Node.js']),
('70572200012', 'M.Vaishnavi', 'vaishnavi.m012@nmims.edu.in', '9059698973', 'B.Tech CSE (DS)', 4, '2022-26', 8.32, 'https://www.linkedin.com/in/vaishnavi-maddi-aa7a4024b/', 'https://github.com/Maddi-vaishnavi', 'Maddi_Vaishnavi', 0, to_jsonb(ARRAY['2nd Position in CodeIT AI4Health; participant of ACM Winter School 2023 on "Data Science for social good", Documentation Head- NMIMS Tech Fiesta 2025(300+ participants)', 'Webathon 2.0 2025']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'Docker', 'AWS']),
('70572200013', 'Akula Srinithya', 'sri.nithya013@nmims.edu.in', '9063284889', 'B.Tech CSE (DS)', 4, '2022-26', 7.22, 'https://www.linkedin.com/in/sri-nithya-a91a8327a/', 'https://github.com/AkulaSrinithya24/GITHUB', 'Akula_Srinithya', 0, to_jsonb(ARRAY['Presented a research project at IICTDS-2025, completed several AI and programming projects as part of my academics, earned an NPTEL certification in Database Management Systems', 'webathon 2024']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'React', 'Node.js']),
('70572200014', 'K.Manishankar Goud', 'manishankar.goud014@nmims.edu.in', '8328486089', 'B.Tech CSE (DS)', 4, '2022-26', 7.25, 'https://www.linkedin.com/in/manishankar-goud-kistaram-363330263', 'https://github.com/Kistaram-Manishankar-Goud', 'Kistaram_Manishankar_Goud', 23, to_jsonb(ARRAY['Selected and participated in  ACM Winter School 2024 on “Decoding AI: Building Explainable and Robust Intelligence”; Published Research Papers in reputed journal like SPRINGER; President of STME Student council NMIMS Hyd.']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'PowerBI', 'Docker']),
('70572200015', 'Jahnavi Maddi', 'jahnavi.m015@nmims.edu.in', '9010351202', 'B.Tech CSE (DS)', 4, '2022-26', 7.65, 'www.linkedin.com/in/maddi-jahnavi-goud', 'https://github.com/Maddi-Jahnavi-goud', 'Maddi_Jahnavi', 0, to_jsonb(ARRAY['Selected for ACM Winter School 2025 on Responsible AI at XIM University,Bhubaneswar.', 'Webathon 2024']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'Docker', 'AWS']),
('70572200017', 'Charala Pujitha', 'pujitha.ch017@nmims.edu.in', '9059603686', 'B.Tech CSE (DS)', 4, '2022-26', 6.87, 'https://www.linkedin.com/in/charala-pujitha-0a3a70257/', 'https://github.com/Charalapujitha', 'CharalaPujitha', 30, to_jsonb(ARRAY['Presented research at IICTDS-2025, developed an industry-oriented Android application (Rupee↔Gram Calculator), participated in IIT Bombay E-Summit 2023, and demonstrated social responsibility through community service initiatives.', 'Webathon 2024']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'React', 'AWS']),
('70572200026', 'J. Thrisha Reddy', 'thrisha.reddy026@nmims.edu.in', '6304624631', 'B.Tech CSE (DS)', 4, '2022-26', 9.50, 'www.linkedin.com/in/thrishareddy12', 'https://github.com/thrisha1217', 'Thrisha_1203', 25, to_jsonb(ARRAY['Head, Research Club (2024–Present): Directed and organized events and initiatives under the Research Club, Co-Head, CyberOwls Club (2023–2024): Managed and facilitated activities and events for the CyberOwls Club,ACM Summer School on AR/VR & HCI interfaces, and immersive interaction using Unity and Meta Quest,ACM Summer school 2024 on compiler design for AI/ML', 'Amazon ML Hackathon 2025 , Participated in IBM Z Datathon 2024']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'React', 'Node.js']),
('70572200027', 'Harsh Bang', 'harsh.bang027@nmims.edu.in', '6305680649', 'B.Tech CSE (DS)', 4, '2022-26', 9.20, 'harshbang - LinkedIn Profile', 'HarshBang - GitHub Profile', 'Harsh_Bang', 90, to_jsonb(ARRAY['Computer Society of India (CSI) Project Expo 2023 Winner (PyGPA Analyzer – 300+ users/semester); Led Coding Club (7+ events); Operations Head-NMIMS Tech Fiesta (300+ participants)', 'AWS Gen AI (Top 20); Analytics Vidya DataHack (Top 7%); Webathon 2.0 (Runner Up); Participated in IBM Z Datathon 2024; Amazon ML Hackathon']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'React', 'AWS']),
('70572200028', 'Ruthvik Akula', 'ruthwik.akula028@nmims.edu.in', '9959557429', 'B.Tech CSE (DS)', 4, '2022-26', 8.50, 'https://www.linkedin.com/in/ruthvik-akula-99106021b/', 'https://github.com/ruth0107', 'ruth_vik', 20, to_jsonb(ARRAY['Built Real Time Ai based products with intrested customers in Healthcare; Got 2ndRunner up price in REL Poster Presentation; Marketing Head-NMIMS Tech Fiesta(300+ participants)', 'Amazon ML Hackathon, Webathon 2.0 (Winners)']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'Docker', 'NLP']),
('70572200030', 'Anmagandla Snehil', 'snehil.a030@nmims.edu.in', '9502605942', 'B.Tech CSE (DS)', 4, '2022-26', 7.80, 'https://www.linkedin.com/in/anmagandla-snehil0108', 'https://github.com/Snehil-0108', 'Snehil_0108', 31, to_jsonb(ARRAY['2nd Position in CodeIT AI4Health;3rd Position in Computer Society India (CSI) Project Expo;ACM Summer School on IoT and Next-Gen Computing – Attended a focused program exploring Internet of Things and Sensor Integration(2025) (IoT), sensor integration, and future computing paradigms.(2025', 'Participated in IBM Z DATATHON; CodeIT Webathon 2024 (Runner Up)']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'NLP', 'AWS']),
('70572200031', 'Narahari Abhinav', 'Abhinav.Narahari031@nmims.edu.in', '7981309655', 'B.Tech CSE (DS)', 4, '2022-26', 6.20, 'www.linkedin.com/in/abhinav-narahari', 'https://github.com/NarahariAbhinav', 'Abhinav_54', 28, to_jsonb(ARRAY['Participated In HelloPm Case Study Competion and got topped in top 10 teams, Developed a Fullstack website to a startup company.', 'Webathon 2024']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'Tableau', 'Docker']),
('70572200032', 'Md Sohail', 'sohail.mohammed032@nmims.edu.in', '7981813039', 'B.Tech CSE (DS)', 4, '2022-26', 7.88, 'https://www.linkedin.com/in/mdsohail032', 'https://www.github.com/sohail262', 'sohail262', 35, to_jsonb(ARRAY['Delivered 2 Power BI Dashboards as products, Delivered 2 Software products to clients', 'Won Webathon 2024; Won Webathon 2025; Runner-up at Six Hours Vibe-Coding Hackathon 2026']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'AWS', 'Node.js']),
('70572200033', 'Malde Saicharan', 'saicharan.m033@nmims.edu.in', '6304856382', 'B.Tech CSE (DS)', 4, '2022-26', 8.07, 'http://www.linkedin.com/in/maldesaicharan', 'https://github.com/saicharan0623', 'saicharanmalde', 180, to_jsonb(ARRAY['Top 50 globally in AWS Skills to Jobs CTF 2025 (2,213 points, 65% solve rate); Technical Head-NMIMS Tech Fiesta (300+ particpants); Delivered 5 Websites and 1 App to clients; Led Cyber Secuirty Club as Head.', 'Runner-up Webathon 2024; Runner-up at Six Hours vibe-coding Hackathon 2026']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'React', 'NLP']),
('70572200034', 'Prasad Sham Kannawar', 'prasad.kannawar034@nmims.edu.in', '8767645336', 'B.Tech CSE (DS)', 4, '2022-26', 7.60, 'www.linkedin.com/in/prasad-kannawar', 'https://github.com/Prasadkannawar', 'prasadkannawar21', 0, to_jsonb(ARRAY['Selected among Top 50 participants in SCDM. Secured 1st Prize in AI Battlefield competition conducted by Analytics Vidhya. Published research paper at IICTDS conference on deep learning-based computer vision applications.', 'SCDM Hackathon; Spark-Wars 4.0 by Celebal Technologies; AI Battlefield Contest; Adobe India Hackathon']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'React', 'Docker']),
('70572200035', 'Venkatesh M', 'venkatesh.m035@nmims.edu.in', '9502340311', 'B.Tech CSE (DS)', 4, '2022-26', 7.00, 'https://www.linkedin.com/in/mahindra-venkatesh/', 'https://github.com/venkatesh-mahindra/', 'Fa5ftp4yJp', 0, to_jsonb(ARRAY['Selected among Top 50 participants in SCDM.Published research paper at IICTDS conference on deep learning-based computer vision applications.President – Cultural Committee ', 'Won Webathon 2024; SCDM Hackathon 2025;']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'React', 'Docker']),
('70572200038', 'Khushal Baldava', 'khushal.baldava038@nmims.edu.in', '7075022092', 'B.Tech CSE (DS)', 4, '2022-26', 6.67, 'https://www.linkedin.com/in/%20khushal-baldava', 'https://github.com/khushal-162004', 'vdutY3xtT8', 25, to_jsonb(ARRAY['Sponsorship Lead, NMIMS Tech Fiesta 2025, PR Head, STME NMIMS Hyderabad, Sonata Software Internship', 'NA']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'PowerBI', 'Docker']),
('70572200042', 'Sidra Fatima', 'sidra.fatima042@nmims.edu.in', '7869250000', 'B.Tech CSE (DS)', 4, '2022-26', 8.13, 'https://www.linkedin.com/in/sidra-fatima-5108102a3/', 'https://github.com/sidrafatima0', 'sidrafatimaraza-', 35, to_jsonb(ARRAY['Head CSI Student Chapter, Head Hostel Committee, IEEE Conference Author,Turtil Internship', 'Rooboshala,Webathon2.0 ']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'Node.js', 'React']),
('70572200044', 'Sai Vijaya Laxmi', 'svijaya.laxmi044@nmims.edu.in', '7569083319', 'B.Tech CSE (DS)', 4, '2022-26', 6.20, 'https://www.linkedin.com/in/sai-vijayalaxmi/', 'https://github.com/Saivijayalaxmi', 'SaiVijayaLaxmi', 26, to_jsonb(ARRAY['NA']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'AWS', 'Node.js']),
('70572200045', 'Vadla Vaishnavi', 'vaishnavi.vadla045@nmims.edu.in', '9908554412', 'B.Tech CSE (DS)', 4, '2022-26', 9.50, 'https://www.linkedin.com/in/vaishnavivadla', 'https://github.com/VaishnaviVadla33', 'vadla_vaishnavi', 100, to_jsonb(ARRAY['Selected for ACM India Winter School 2025 (Responsible AI). Received Letter of Appreciation from the Additional District Collector, Mahabubnagar for deploying MBNR VidyaEye across 100+ government hostels. Ranked Top 20% in NMIMS Research Symposium. Currently working on a real-time AI Automation project.', 'IBM Z Datathon 2024; Amazon ML Hackathon 2025; CodeIt Webathon 2.0; Flipkart Grid ']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'Tableau', 'NLP']),
('70572200046', 'B Vaishnavi', 'vaishnavi.b046@nmims.edu.in', '9490205969', 'B.Tech CSE (DS)', 4, '2022-26', 8.65, 'https://www.linkedin.com/in/vaishnavibyagari/', 'https://github.com/vaishnaviByagari', 'vaishnavibyagari', 0, to_jsonb(ARRAY['NA']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'React', 'Node.js']),
('70572200047', 'G. Sainath Goud', 'sainath.goud047@nmims.edu.in', '6304342760', 'B.Tech CSE (DS)', 4, '2022-26', 7.00, 'https://www.linkedin.com/in/sainathgoudgoda/', 'https://github.com/SAINATH0224', 'NA', 0, to_jsonb(ARRAY['IEEE Conference Publication: “Real-Time Safety System for Highway Crossovers Using Vision-Based Detection and Early Warning Alerts”, presented at IIT Dharwad.', 'NA']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'React', 'Node.js']),
('70572200049', 'Kurumidde John Austin', 'john.austin049@nmims.edu.in', '8096448937', 'B.Tech CSE (DS)', 4, '2022-26', 5.70, 'www.linkedin.com/in/john-austin-kurumidde', 'https://github.com/JohnAustin18', 'NA', 0, to_jsonb(ARRAY['Top 75 in Poster Symposium on Research Embedded Learning 2025', 'AI for Health Hackthon-2025']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'Docker', 'React']),
('70572200050', 'Chetan H', 'chetan.h050@nmims.edu.in', '8317529342', 'B.Tech CSE (DS)', 4, '2022-26', 7.00, 'https://www.linkedin.com/in/h-chetan-goud-550278283/', 'https://github.com/Chetangoud24', 'NA', 0, to_jsonb(ARRAY['IEEE Conference Author (IIT Dharwad); Data Science Intern at Karvic; Built real-time AI systems using YOLOv8 (Elephant Detection, Crosswalk Monitoring, Drowsiness Detection)', 'Webathon 2024']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'React', 'Node.js']),
('70572200052', 'Ananya P', 'Ananya.reddy052@nmims.edu.in', '9502553373', 'B.Tech CSE (DS)', 4, '2022-26', 0.08, 'https://www.linkedin.com/in/ananya-peddamgari-a6311026a', 'https://github.com/Ananya-Peddamgari/Ananya-Peddamgari', 'RP5WDc6D3y', 75, to_jsonb(ARRAY['Webathon 2024,2025']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'Computer Vision', 'PowerBI']),
('70572200053', 'M Sowmya', 'sowmya.makam053@nmims.edu.in', '7337270506', 'B.Tech CSE (DS)', 4, '2022-26', 8.70, 'https://www.linkedin.com/in/sowmya-makam/', 'https://github.com/Sowmyamaakam', '', 100, to_jsonb(ARRAY['Webathon 2024']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'React', 'Docker']),
('70572200054', 'G Pragnya Reddy', 'pragnya.reddy054@nmims.edu.in', '9100431881', 'B.Tech CSE (DS)', 4, '2022-26', 8.25, 'https://www.linkedin.com/in/pragnyareddygudyagopu/', 'https://github.com/pragnyareddy00', 'pragnyareddy054', 0, to_jsonb(ARRAY[' Got 2ndRunner up price in REL Poster Presentation', 'Webathon 2024']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'Docker', 'React']),
('70572200055', 'V Abhiram Reddy', 'VAbhiram.reddy055@nmims.edu.in', '7780720178', 'B.Tech CSE (DS)', 4, '2022-26', 6.20, 'https://www.linkedin.com/in/abhiramreddyvundhyala/', 'https://github.com/Abhiramreddyvundhyala', 'NA', 0, to_jsonb(ARRAY['IEEE Conference Publication: “Real-Time Safety System for Highway Crossovers Using Vision-Based Detection and Early Warning Alerts”, presented at IIT Dharwad,Received official Letter of Appreciation from the Additional District Collector, Mahabubnagar, for developing and deploying a district-level mobile & web application (MBNR Vidya Eye) used across 100+ government hostels to enhance transparency and digital governance.', 'IBM Z DATATHON; CodeIT Webathon 2024 (Runner Up); Top 100  in Apoorv CTF ''24; ']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'AWS', 'Computer Vision']),
('70572200056', 'Rudramoni Ananth Yadav', 'yadavr.ananth056@nmims.edu.in', '9705431557', 'B.Tech CSE (DS)', 4, '2022-26', 7.53, 'https://www.linkedin.com/in/rudramoni-ananth-yadav/', 'https://github.com/RudramoniAnanth/', 'rudramoniananth1', 0, to_jsonb(ARRAY['2nd Position in CodeIT AI4Health; 3rd Position in Computer Society India (CSI) Project Expo; Top 75 in Poster Symposium on Research Embedded Learning 2025;  Worked as Technical Lead & Full-Stack Developer For MBNR VidyaEye  (100+ users)', 'Participated in IBM Z DATATHON; CodeIT Webathon 2024 (Runner Up); Top 100  in Apoorv CTF ''24; Participated in Anveshanam ; ']), ARRAY['Python', 'SQL', 'Data Science', 'Machine Learning', 'Algorithms', 'System Design', 'React', 'Node.js'])
ON CONFLICT (sap_id) DO UPDATE SET 
    name = EXCLUDED.name,
    email = EXCLUDED.email,
    cgpa = EXCLUDED.cgpa,
    linkedin_url = EXCLUDED.linkedin_url,
    github_url = EXCLUDED.github_url,
    leetcode_total_solved = EXCLUDED.leetcode_total_solved,
    achievements = EXCLUDED.achievements,
    skills = EXCLUDED.skills;

-- SECURITY NOTICE:
-- Ensure your RLS policies allow selection by admins to see this data.
